# Setup
title:        Pardhu Madipalli
tagline:      A full-stack cloud developer with more than 2 years of experience.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Pardhu Madipalli
  email:      pardhu1212@gmail.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
