# global settings
title: Pardhu Madipalli
description: "Website of Pardhu Madipalli"
url: https://pardhumadipalli.github.io
locale: "en"
relative_permalinks: false

# About/contact
author:
  name: Pardhu Madipalli
  email: pardhu1212@gmail.com
  twitter: pardhumadipalli

twitter:
  username: pardhumadipalli
  card: summary

social:
  name: Pardhu Madipalli
  links:
    - https://twitter.com/pardhumadipalli
    - https://www.facebook.com/pardhu1212
    - https://www.linkedin.com/in/pardhumadipalli
    - https://github.com/PardhuMadipalli

# build settings
exclude: ["script", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "package.json", "package-lock.json", "node_modules", "vendor"]
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

webrick:
  headers:
    Cache-Control: max-age=0
