# global settings
title: Pardhu Madipalli
description: "Profile of Pardhu Madipalli"
url: https://pardhumadipalli.github.io
locale: "en"
relative_permalinks: false

# About/contact
author:
  name:       Pardhu Madipalli
  email:      pardhu1212@gmail.com

# build settings
exclude: ["script", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
