name: Jekyll Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Jekyll-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build the site using bundler
      run: bundle exec jekyll build

